const inputElement = document.querySelector('#input')
const fromElement = document.querySelector('#from')
const toElement = document.querySelector('#to')
const outputElement = document.querySelector('#output')
const convertButton = document.querySelector('#convert-btn')
const messageElement = document.querySelector('#message')